# Generated by Django 2.2 on 2019-05-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, null=True)),
                ('date', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=1, null=True)),
                ('mark', models.PositiveSmallIntegerField(null=True)),
                ('study_year', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('pos', models.CharField(choices=[('ADV', 'ADV'), ('ADJ', 'ADJ'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('VERB', 'VERB'), ('PROPN', 'PROPN'), ('ADP', 'ADP'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('SCONJ', 'SCONJ'), ('PUNCT', 'PUNCT'), ('SYM', 'SYM'), ('X', 'X')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('xpos', models.CharField(max_length=5, null=True)),
                ('lemma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpustool.Lemma')),
            ],
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpustool.Document')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpustool.Token')),
            ],
        ),
        migrations.CreateModel(
            name='DepRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typerel', models.CharField(max_length=50)),
                ('dependant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependant', to='corpustool.Occurence')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='corpustool.Occurence')),
            ],
        ),
    ]
